language: groovy
branches:
  only:
    - master
before_install:
 - sudo add-apt-repository -y ppa:groovy-dev/grails
 - sudo apt-get update
 - sudo apt-get -y install grails-ppa
 - sudo apt-get install grails 2.2.0

script: grails test refresh-dependencies && grails test test-app
